// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_tlo = NULL;
lv_obj_t * ui_wskaznik = NULL;
lv_obj_t * ui_SpeedLabel = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_tlo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        gaugePress(e);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tlo = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_tlo, &ui_img_tlo_nospeed_dither2_png);
    lv_obj_set_width(ui_tlo, LV_SIZE_CONTENT);   /// 466
    lv_obj_set_height(ui_tlo, LV_SIZE_CONTENT);    /// 466
    lv_obj_set_align(ui_tlo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tlo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_tlo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wskaznik = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_wskaznik, &ui_img_wskaznik_crop_png);
    lv_obj_set_width(ui_wskaznik, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_wskaznik, LV_SIZE_CONTENT);    /// 254
    lv_obj_set_x(ui_wskaznik, 0);
    lv_obj_set_y(ui_wskaznik, 82);
    lv_obj_set_align(ui_wskaznik, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wskaznik, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wskaznik, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_wskaznik, 45, 45);
    lv_img_set_angle(ui_wskaznik, 6);
    lv_obj_set_style_transform_angle(ui_wskaznik, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, -41);
    lv_obj_set_y(ui_SpeedLabel, 52);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_SpeedLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_SpeedLabel, "000");
    lv_obj_set_style_text_font(ui_SpeedLabel, &ui_font_UbuntumediumItalic84, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 163);
    lv_obj_set_y(ui_Label2, -35);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "N");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_UbuntuMediumItalic66, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Image2, &ui_img_triangle_small_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 46
    lv_obj_set_x(ui_Image2, 88);
    lv_obj_set_y(ui_Image2, -32);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_tlo, ui_event_tlo, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_tlo = NULL;
    ui_wskaznik = NULL;
    ui_SpeedLabel = NULL;
    ui_Label2 = NULL;
    ui_Image2 = NULL;

}
