// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#include "ui.h"

void gaugePress(lv_event_t * e)
{
	// play animation 
	// gauge_Animation(ui_wskaznik, 0);

}


