// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#ifndef _OBD_DISPLAY_UI_H
#define _OBD_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_HeloScreen.h"
#include "screens/ui_MainScreen.h"
#include "screens/ui_ConfigScreen.h"
#include "screens/ui_ConfigScreen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * Logo_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * gauge_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_ifa_logo466_blackbg_png);    // assets/ifa_logo466_blackBG.png
LV_IMG_DECLARE(ui_img_tlo_nospeed_dither2_png);    // assets/tlo_nospeed_dither2.png
LV_IMG_DECLARE(ui_img_wskaznik_crop_png);    // assets/wskaznik_crop.png
LV_IMG_DECLARE(ui_img_triangle_small_png);    // assets/triangle_small.png

// FONTS
LV_FONT_DECLARE(ui_font_UbuntumediumItalic84);
LV_FONT_DECLARE(ui_font_UbuntuMediumItalic66);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
