// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#include "../ui.h"

lv_obj_t * ui_ConfigScreen1 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
// event funtions

// build funtions

void ui_ConfigScreen1_screen_init(void)
{
    ui_ConfigScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConfigScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigScreen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_ConfigScreen1);
    lv_dropdown_set_dir(ui_Dropdown1, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown1, "a	\nb\nc\nd\ne\nf\ng\nh\ni\nj\nk\nl\nm\nn\no\np");
    lv_dropdown_set_text(ui_Dropdown1, "Bluetooth Device");
    lv_obj_set_width(ui_Dropdown1, 250);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, -215);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_radius(ui_Dropdown1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dropdown1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dropdown1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dropdown1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dropdown1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_ConfigScreen1, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 150);
    lv_obj_set_height(ui_Spinner2, 150);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Spinner2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_ConfigScreen1_screen_destroy(void)
{
    if(ui_ConfigScreen1) lv_obj_del(ui_ConfigScreen1);

    // NULL screen variables
    ui_ConfigScreen1 = NULL;
    ui_Dropdown1 = NULL;
    ui_Spinner2 = NULL;

}
