// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#ifndef UI_CONFIGSCREEN1_H
#define UI_CONFIGSCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConfigScreen1
extern void ui_ConfigScreen1_screen_init(void);
extern void ui_ConfigScreen1_screen_destroy(void);
extern lv_obj_t * ui_ConfigScreen1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Spinner2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

