// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#ifndef UI_CONFIGSCREEN_H
#define UI_CONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConfigScreen
extern void ui_ConfigScreen_screen_init(void);
extern void ui_ConfigScreen_screen_destroy(void);
extern lv_obj_t * ui_ConfigScreen;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label4;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

