// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#include "../ui.h"
#include "../../settings.h"
#include "../../ui_SimsonScreen.h"

lv_obj_t * ui_HeloScreen = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_HeloScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        int theme = settings_get_theme();
        if (theme == 1) {
            _ui_screen_change(&ui_SimsonScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000, &ui_SimsonScreen_screen_init);
        } else if (theme == 2) {
            // ui_SimsonScreen_screen_init() builds both day and night variants.
            _ui_screen_change(&ui_SimsonNightScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000, &ui_SimsonScreen_screen_init);
        } else {
            _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 3000, &ui_MainScreen_screen_init);
        }
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        int theme = settings_get_theme();
        if (theme == 0) {
            gauge_Animation(ui_wskaznik, 500);
        }
    }
}

// build funtions

void ui_HeloScreen_screen_init(void)
{
    ui_HeloScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HeloScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeloScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeloScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeloScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_HeloScreen);
    lv_img_set_src(ui_Image1, &ui_img_ifa_logo466_blackbg_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 390
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 312
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Image1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HeloScreen, ui_event_HeloScreen, LV_EVENT_ALL, NULL);

}

void ui_HeloScreen_screen_destroy(void)
{
    if(ui_HeloScreen) lv_obj_del(ui_HeloScreen);

    // NULL screen variables
    ui_HeloScreen = NULL;
    ui_Image1 = NULL;

}
