// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OBD_DISPLAY

#ifndef UI_HELOSCREEN_H
#define UI_HELOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HeloScreen
extern void ui_HeloScreen_screen_init(void);
extern void ui_HeloScreen_screen_destroy(void);
extern void ui_event_HeloScreen(lv_event_t * e);
extern lv_obj_t * ui_HeloScreen;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

